# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20171018_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen_categoria',
            field=models.ImageField(default='', upload_to='static/images/%Y/%m'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='static/images/%Y/%m'),
        ),
    ]
