# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0004_auto_20171018_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='img/%Y/%m'),
        ),
    ]
