# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 02:49
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0006_auto_20171018_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='imagen_categoria',
            field=models.ImageField(upload_to='media/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='media/%Y/%m'),
        ),
    ]
