# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0008_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256)),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Imagen')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.Libro')),
            ],
        ),
    ]
