# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 03:25
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0009_capitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libros.Imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='introduccion',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
    ]
