# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 04:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0011_auto_20171021_0044'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='capitulo',
            unique_together=set([('libro', 'orden')]),
        ),
    ]
