# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0012_auto_20171021_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasImportantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria1', to='libros.Categoria')),
                ('categoria2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria2', to='libros.Categoria')),
                ('categoria3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria3', to='libros.Categoria')),
                ('categoria4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria4', to='libros.Categoria')),
            ],
        ),
    ]
