# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0013_categoriasimportantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosDestacados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro1', to='libros.Libro')),
                ('libro2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro2', to='libros.Libro')),
                ('libro3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro3', to='libros.Libro')),
                ('libro4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libro4', to='libros.Libro')),
            ],
        ),
        migrations.RemoveField(
            model_name='categoriasimportantes',
            name='categoria1',
        ),
        migrations.RemoveField(
            model_name='categoriasimportantes',
            name='categoria2',
        ),
        migrations.RemoveField(
            model_name='categoriasimportantes',
            name='categoria3',
        ),
        migrations.RemoveField(
            model_name='categoriasimportantes',
            name='categoria4',
        ),
        migrations.DeleteModel(
            name='CategoriasImportantes',
        ),
    ]
