# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0014_auto_20171023_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='calificacion',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
