# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0017_auto_20171025_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='calificacion',
        ),
    ]
