# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0018_remove_libro_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='calificacion',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
