# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0023_libro_es_publico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librosdestacados',
            name='libro1',
        ),
        migrations.RemoveField(
            model_name='librosdestacados',
            name='libro2',
        ),
        migrations.RemoveField(
            model_name='librosdestacados',
            name='libro3',
        ),
        migrations.RemoveField(
            model_name='librosdestacados',
            name='libro4',
        ),
        migrations.AlterField(
            model_name='libro',
            name='calificacion',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='LibrosDestacados',
        ),
    ]
