# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0026_content'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Contenido',
        ),
    ]
