# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0027_auto_20171031_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='numero',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
