# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0031_autoevaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='puntaje',
            field=models.PositiveIntegerField(choices=[(0, b'0'), (1, b'1'), (2, b'2'), (3, b'3'), (4, b'4'), (5, b'5')], default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Categoria'),
        ),
    ]
