# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0034_auto_20171107_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='pregunta',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
