# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 02:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0038_auto_20171112_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=127)),
                ('iso', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='categoria',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.TipoPregunta'),
        ),
    ]
