# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0040_tipopregunta_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipopregunta',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Categoria'),
        ),
    ]
