# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0041_tipopregunta_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoevaluacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='libro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='libros.Libro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autoevaluacion',
            name='pregunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Pregunta'),
        ),
        migrations.AlterField(
            model_name='autoevaluacion',
            name='opcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libros.Opcion'),
        ),
    ]
